
# docker-compose.yml
services:
  db:
    image: ankane/pgvector:latest
    container_name: rag_db
    restart: always
    environment:
      POSTGRES_DB: headhunter_db 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # This correctly exposes the database port to your local machine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingestion:
    build: . # Builds from the Dockerfile in the current directory
    container_name: rag_ingestion
    command: python3 load_relational_and_vector_databases.py
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db 
      - POSTGRES_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  api:
    build: . # Builds from the same Dockerfile
    container_name: rag_api
    restart: always
    # --- THIS IS THE CORRECTED LINE ---
    # It maps the container's web port (8000) to your computer's port (8000)
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: